apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy-node-gateway.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "proxy-node-gateway.name" . }}-redis
    helm.sh/chart: {{ include "proxy-node-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-redis
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/name: {{ include "proxy-node-gateway.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
