apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxy-node-gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "proxy-node-gateway.name" . }}
    helm.sh/chart: {{ include "proxy-node-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "proxy-node-gateway.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "proxy-node-gateway.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
        - name: mgmt
          containerPort: 6601
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: mgmt
          initialDelaySeconds: 20
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 20
          periodSeconds: 5
        env:
        - name: PORT
          value: "80"
        - name: REDIS_SERVER_URI
          value: redis://{{ .Release.Name }}-gateway-redis:6379/
        - name: TRANSLATOR_URL
          value: http://{{ .Release.Name }}-translator:6300/SAML2/SSO/Response/POST
        - name: EIDAS_SAML_PARSER_URL
          value: http://{{ .Release.Name }}-parser:6400/
        - name: VERIFY_SERVICE_PROVIDER_URL
          value: http://127.0.0.1:8080/ # this needs to be set to the actual vsp when we have it
