apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxy-node-gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "proxy-node-gateway.name" . }}
    helm.sh/chart: {{ include "proxy-node-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 31200
    targetPort: http
  - name: mgmt
    port: 6601
    targetPort: mgmt
  selector:
    app.kubernetes.io/name: {{ include "proxy-node-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
