apiVersion: v1
kind: Service
metadata:
  name: {{ include "stub-connector.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "stub-connector.name" . }}
    helm.sh/chart: {{ include "stub-connector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 31100
    targetPort: http
  - name: mgmt
    port: 6667
    targetPort: mgmt
  selector:
    app.kubernetes.io/name: {{ include "stub-connector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
