apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stub-connector.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "stub-connector.name" . }}
    helm.sh/chart: {{ include "stub-connector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "stub-connector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "stub-connector.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.stubConnector.image.repository }}:{{ .Values.stubConnector.image.tag }}"
        imagePullPolicy: {{ .Values.stubConnector.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
        - name: mgmt
          containerPort: 6667
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: mgmt
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: CONNECTOR_NODE_BASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-stub-connector-pki
              key: CONNECTOR_NODE_BASE_URL
        - name: ENCRYPTION_CERT
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-stub-connector-pki
              key: ENCRYPTION_CERT
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-stub-connector-pki
              key: ENCRYPTION_KEY
        - name: PORT
          value: "80"
        - name: PROXY_NODE_ENTITY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-stub-connector-pki
              key: PROXY_NODE_ENTITY_ID
        - name: PROXY_NODE_METADATA_FOR_CONNECTOR_NODE_URL
          value: http://{{ .Release.Name }}-stub-metadata/metadata_for_connector_node.xml
        - name: PROXY_NODE_METADATA_TRUSTSTORE
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-stub-connector-pki
              key: PROXY_NODE_METADATA_TRUSTSTORE
        - name: PROXY_NODE_METADATA_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-stub-connector-pki
              key: PROXY_NODE_METADATA_TRUSTSTORE_PASSWORD
        - name: SIGNING_CERT
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-stub-connector-pki
              key: SIGNING_CERT
        - name: SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-stub-connector-pki
              key: SIGNING_KEY
