apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxy-node-translator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "proxy-node-translator.name" . }}
    helm.sh/chart: {{ include "proxy-node-translator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "proxy-node-translator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "proxy-node-translator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      volumes:
        - name: proxy-node-pki
          secret:
            secretName: {{ .Release.Name }}-proxy-node-pki
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
        - name: mgmt
          containerPort: 6661
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: mgmt
          initialDelaySeconds: 20
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 20
          periodSeconds: 5
        volumeMounts:
          - mountPath: /app/keys/
            name: proxy-node-pki
            readOnly: true
        env:
        - name: PORT
          value: "80"
        - name: PROXY_NODE_METADATA_FOR_CONNECTOR_NODE_URL
          value: http://{{ .Release.Name }}-stub-metadata/metadata_for_connector_node.xml
        - name: SOFT_HSM_SIGNING_KEY_PIN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-hsm
              key: signingKeyPIN
        - name: SOFT_HSM_SIGNING_KEY_LABEL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-hsm
              key: signingKeyLabel
        - name: CONNECTOR_NODE_ISSUER_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-proxy-node-pki
              key: CONNECTOR_NODE_ISSUER_ID
        - name: SIGNING_CERT
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-proxy-node-pki
              key: SIGNING_CERT
        - name: SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-proxy-node-pki
              key: SIGNING_KEY
