replicaCount: 1
image:
  repository: registry.tools.verify.govsvc.uk/eidas/cloudhsm
  tag: latest
  pullPolicy: IfNotPresent

signingKeyPIN: "fake:user"
signingKeyLabel: vfpn-uk-signing
signingKeyToken: vfpn-uk-signing
signingKeySlot: "0"
signingKeyID: DEF0
signingKeySOPIN: "fake:user"

