apiVersion: v1
kind: Service
metadata:
  name: {{ include "eidas-saml-parser.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "eidas-saml-parser.name" . }}
    helm.sh/chart: {{ include "eidas-saml-parser.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 31400
    targetPort: http
    protocol: TCP
  - name: mgmt
    port: 6008
    targetPort: mgmt
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "eidas-saml-parser.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
