apiVersion: v1
kind: Service
metadata:
  name: {{ include "softhsm.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "softhsm.name" . }}
    helm.sh/chart: {{ include "softhsm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: pkcs11
    port: 5656
    targetPort: pkcs11
  selector:
    app.kubernetes.io/name: {{ include "softhsm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
