apiVersion: v1
kind: Secret
metadata:
  name: {{ include "softhsm.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "softhsm.name" . }}
    helm.sh/chart: {{ include "softhsm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  signingKeyPIN: {{ .Values.signingKeyPIN | b64enc | quote }}
  signingKeyLabel: {{ .Values.signingKeyLabel | b64enc | quote }}
  signingKeyToken: {{ .Values.signingKeyToken | b64enc | quote }}
  signingKeySlot: {{ .Values.signingKeySlot | b64enc | quote }}
  signingKeyID: {{ .Values.signingKeySlot | b64enc | quote }}
  signingKeySOPIN: {{ .Values.signingKeySOPIN | b64enc | quote }}
